In [3]:
import numpy as np
import scipy.spatial.distance as spd
import pickle
from numpy.linalg import pinv
from sklearn.metrics import confusion_matrix

## EX1

In [4]:
X0 =np.array([[2, 1, -1, 2, 2] , [2, -2, -2, 0, -2]])
X1 =np.array([[3, 5, 4, 4] , [2, 1, 2, 2]])

m0 = np.mean(X0, axis=1)
m1 = np.mean(X1, axis=1)

### A))

In [5]:
cov0 = np.cov(X0)
S0i = pinv(cov0)
cov1 = np.cov(X1)
S1i = pinv(cov1)

X = [np.array([-4, 0]).T, np.array([-1, -1]).T]

D0 = np.sqrt(np.sum((X-m0[:,np.newaxis])*np.dot(S0i,X-m1[:,np.newaxis]), axis=0))
D1 = np.sqrt(np.sum((X-m1[:,np.newaxis])*np.dot(S1i,X-m1[:,np.newaxis]), axis=0))

D = np.vstack((D0, D1))
ye = np.argmin(D, axis = 0)

print(ye)

# A) [1,0,0,0]

[0 0]


### B))

In [6]:
x0 = np.round(X0)
x1 = np.round(X1)
X = np.hstack((x0, x1))

In [7]:
## Fazer matriz de confusao
nx = np.sqrt(np.sum(X**2 , axis=0))
xn = X/nx

m0n = m0/np.sqrt(np.sum(m0**2))
m1n = m1/np.sqrt(np.sum(m1**2))

M = np.vstack((m0n, m1n))
D = 1 - np.dot(M,xn)

ye=np.argmin(D,axis=0)
y =np.array([0,0,0,0,0,1,1,1,1])


print(ye)
print('total ' , np.sum(y!=ye))
print('matriz\n' , confusion_matrix(y,ye))

# B ) [0,0,0,1]

[1 0 0 1 0 1 1 1 1]
total  2
matriz
 [[3 2]
 [0 4]]


### C))

In [8]:
from scipy.spatial.distance import pdist

m = np.vstack((m0.T,m1.T))

man_dist = pdist(m, 'cityblock')
cos_dist = pdist(m, 'cosine')

print('man ' , np.round(man_dist, 2))
print('cos ' , np.round(cos_dist, 2))

man2 = np.sum(np.abs(m0-m1),axis=0)
print(man2)

# C ) [0,1,0,0]

man  [5.35]
cos  [0.46]
5.35


### D))

In [9]:
D0 = np.sqrt(np.sum((X-m0[:, np.newaxis])**2, axis = 0))
D1 = np.sqrt(np.sum((X-m1[:, np.newaxis])**2, axis = 0))

D = np.vstack((D0,D1))
print(D)
ye=np.argmin(D,axis=0)
y =np.array([0,0,0,0,0,1,1,1,1])


print(ye)
print('total ' , np.sum(y!=ye))
print('matriz\n' , confusion_matrix(y,ye))


# D ) [0,1,0,0]

[[2.91204396 1.21655251 2.50599282 1.13137085 1.44222051 3.3286634
  4.20475921 3.95979797 3.95979797]
 [2.01556444 4.80234318 6.25       2.65753645 4.25       1.03077641
  1.25       0.25       0.25      ]]
[1 0 0 0 0 1 1 1 1]
total  1
matriz
 [[4 1]
 [0 4]]


### E))

In [10]:
X = np.array([np.array([1,-2]).T, np.array([-2,-4]).T])

D0 = np.sum(np.abs(X-m0), axis=0)
D1 = np.sum(np.abs(X-m1), axis=0)

D = np.vstack((D0, D1))
ye = np.argmin(D, axis = 0)
print(ye)

# E) [0,0,1,0]

[0 0]


## EX 2

In [11]:
fName = 'A45415_Q002_data.p'
D = pickle.load(open(fName, 'rb'))

### A)

In [12]:
print(confusion_matrix(D['trueClass'] , D['estClass']).T)
print(D['trueClass'])
# A) [0,1,0,0]

[[1102   84]
 [ 158  456]]
[1. 1. 1. ... 0. 0. 0.]


### B)

In [13]:
print(round(1102/(1102+158), 3))
print(round(158/(1102+158), 3))

# B) [0,0,1,0]

0.875
0.125


### C)

In [14]:
print(np.sum(D['trueClass'])/len(D['trueClass']))

# C) [0,1,0,0]

0.3


## EX 3

In [18]:
from sklearn.neighbors import KNeighborsClassifier

fName = 'A45415_Q003_data.p'
D = pickle.load(open(fName, 'rb'))

X = D['X']
y = D['trueClass']
xTrain = D['Xtrain']
xTest = D['Xtest']
yTrain = D['trueClassTrain']
yTest = D['trueClassTest']

### A)

In [23]:
def myMetric(x,y):
    m = np.array([np.array([1,-2]) , np.array([1,1])])
    return np.dot(np.dot((x-y).T, m) , (x-y))


knn = KNeighborsClassifier(n_neighbors=19, metric=myMetric, algorithm='brute').fit(xTrain.T, yTrain)
y2e = knn.predict(xTest.T)
print('erros ',np.sum(y2e != yTest))
print('matriz\n', confusion_matrix(yTest,y2e))

# A) [1,0,0,0]
# B) [1,0,0,0]

erros  7
matriz
 [[103   1   0]
 [  0 194   0]
 [  6   0 217]]


In [17]:
import pickle, numpy as np
dictionary = pickle.load(open('A45415_Ficha2_Respostas.p', 'rb'))

dictionary['Q001'][0,:] = np.array([1,0,0,0])
dictionary['Q001'][1,:] = np.array([0,0,0,1])
dictionary['Q001'][2,:] = np.array([0,1,0,0])
dictionary['Q001'][3,:] = np.array([0,1,0,0])
dictionary['Q001'][4,:] = np.array([0,0,1,0])

dictionary['Q002'][0,:] = np.array([0,1,0,0])
dictionary['Q002'][1,:] = np.array([0,0,1,0])
dictionary['Q002'][2,:] = np.array([0,1,0,0])

dictionary['Q003'][0,:] = np.array([0,0,0,1])
dictionary['Q003'][1,:] = np.array([0,0,0,1])

pickle.dump(dictionary, open('A45415_Ficha2_Respostas.p','wb'))

In [1]:
dictionary

NameError: name 'dictionary' is not defined