In [1]:
import pickle
import numpy as np
import scipy.linalg as la
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
import sklearn.datasets as DT
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import Ridge,Lasso
from sklearn.metrics import confusion_matrix

In [14]:
#Exercicio 1

D=pickle.load(open('A46296_Q001_data.p','rb'))


x=D['x']
#print(x.shape)
y=D['y']
#print(y.shape)
fd=D['folds']
#print(fd.shape)


X1 = x[fd==0]
X1 = X1[:,np.newaxis]
X2 = x[fd==1]
X2 = X2[:,np.newaxis]
y1 = y[fd==0]
y1 = y1[:,np.newaxis]
y2 = y[fd==1]
y2 = y2[:,np.newaxis]

#alinea a) 0001

#X1 - treino
#X2 - teste
poly=PolynomialFeatures(4,include_bias=False).fit(X1)
X1a=poly.transform(X1)
X2a=poly.transform(X2)
rl=LinearRegression().fit(X1a,y1)
# i
y2e =rl.predict(X1a)
print(mean_absolute_error(y1,y2e))
# ii
print(rl.intercept_)

#alinea b) 0010

#X2 - treino
#X1 - teste

poly=PolynomialFeatures(3,include_bias=False).fit(X2)
X1a=poly.transform(X1)
X2a=poly.transform(X2)

rl=LinearRegression().fit(X2a,y2) #treinoooo

y1e =rl.predict(X1a) #teste
print(np.sum((abs(y1-y1e))/len(y1),axis=0))


y2e =rl.predict(X2a) #treino
print(np.sum((abs(y2-y2e))/len(y2),axis=0))


#alinea c) 0010

Xc = x[:126]
Xc = Xc[:,np.newaxis]
yc = y[:126] 
yc = yc[:,np.newaxis]
poly=PolynomialFeatures(4,include_bias=False).fit(Xc)
lr_a=LinearRegression().fit(Xc,yc)
print(lr_a.score(Xc,yc))

poly=PolynomialFeatures(4,include_bias=False).fit(X1)
lr_b=LinearRegression().fit(X1,y1)
print(lr_b.score(X1,y1))

w = lr_b.coef_
print(w.max())


0.10157359759624857
[-8.89988113]
[48.8255024]
[0.38172748]
8.859821163986759e-05
0.9611790810259478
-1.1639004059924563


[-318.26925335  139.97079677  -20.06765782    0.94369298]
0.3817274853243355


In [13]:
#Exercicio 2

D = DT.load_diabetes()


X = D.data
Y = D.target

x_treino = X[:219]
y_treino = Y[:219]

x_teste = X[219:]
y_teste = Y[219:]


#Alinea C 0100
poly = PolynomialFeatures(degree = 2, include_bias = False).fit(x_treino)
X1a = poly.transform(x_treino)
X2a = poly.transform(x_teste)



rl = LinearRegression().fit(X1a,y_treino)

print(rl.score(X2a,y_teste))
ytestPred = rl.predict(X2a)
print(mean_squared_error(y_teste,ytestPred))

w = rl.coef_
print(w.shape) #Alinea A 0001


#Alinea B 1000

poly = PolynomialFeatures(degree = 4, include_bias = False).fit(x_treino)
X1a = poly.transform(x_treino)
X2a = poly.transform(x_teste)


rl = Lasso(random_state = 42, alpha=0.01).fit(X1a,y_treino)

print(round(rl.score(X1a,y_treino),2))

w = rl.coef_

print(np.sum(abs(w) >= 253))


0.42159515481276544
3570.2784566951
(65,)
0.52
10


In [130]:
#Exercicio 3

#Alinea a) - 1000

D = pickle.load(open('A46296_Q003_data.p','rb'))

x = D['X']*1.
y = D['y']

#print(x.shape)


X1 = np.vstack((np.ones(2393),x)) #o 2393 é preciso ver a shape do x
yb = (y > 0)*2-1


w = np.array([0.00,0.29,0.96])
y1e = np.dot(w.T, X1)
yeb = (y1e > 0)*2-1

MC = confusion_matrix(yb,yeb)
print(MC)

recall = 1727/(1727+118)
print(round(recall,3))

[[ 377  171]
 [ 118 1727]]
0.936


In [132]:
#Alinea b) - 1000

X1 = np.vstack((np.ones(2393),x))
yb = (y > 0)*2-1

Rx = np.dot(X1, X1.T)
ryx=np.dot(X1,yb.T)
w=np.dot(la.pinv(Rx),ryx)

print(w)



ye = np.dot(w.T,X1)
yeb=(ye>0)*2-1

MC = confusion_matrix(yb,yeb)
print(MC)



[0.23635187 0.20491407 0.15873401]
[[ 379  169]
 [   0 1845]]


In [134]:
#Alinea c) - 1000

w = np.array([0.00,0.03,1.00])
yb = (y > 0)*2-1
y1e = np.dot(w.T,X1)

yeb = (y1e>0)*2-1

MC = confusion_matrix(yb,yeb)
print(MC)

recall = 1608/(1608+237)
print(round(recall,3))


[[ 332  216]
 [ 237 1608]]
0.872


In [15]:
Respostas = 'A46296_Ficha4_Respostas.p'
R = pickle.load(open(Respostas,'rb'))

In [16]:
R['Q001'][0,:]=np.array([0,0,0,1]) 
R['Q001'][1,:]=np.array([0,0,1,0]) 
R['Q001'][2,:]=np.array([0,0,1,0]) 

R['Q002'][0,:]=np.array([0,0,0,1]) 
R['Q002'][1,:]=np.array([1,0,0,0]) 
R['Q002'][2,:]=np.array([0,1,0,0]) 

R['Q003'][0,:]=np.array([1,0,0,0])  
R['Q003'][1,:]=np.array([1,0,0,0]) 
R['Q003'][2,:]=np.array([1,0,0,0])

In [17]:
pickle.dump(R,open(Respostas,'wb'))

In [18]:
R

{'Q001': array([[0., 0., 0., 1.],
        [0., 0., 1., 0.],
        [0., 0., 1., 0.]]),
 'Q002': array([[0., 0., 0., 1.],
        [1., 0., 0., 0.],
        [0., 1., 0., 0.]]),
 'Q003': array([[1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.]]),
 'nome': 'Tiago Miguel Da Silva Gil',
 'numero': 'A46296'}